services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-crm-php
    container_name: crm_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    #   - redis # Если используется для кеша/очередей

  nginx:
    image: nginx:stable-alpine
    container_name: crm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - db

  db:
    image: postgres:16-alpine
    container_name: crm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mini_crm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
