services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-crm-php
    container_name: crm_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db

    user: www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=mini_crm
      - DB_USERNAME=root
      - DB_PASSWORD=root

    command: /bin/sh -c "sleep 5 && 
      composer install --ignore-platform-reqs --optimize-autoloader && 
      npm install && if [ ! -f .env ]; then cp .env.example .env; php artisan key:generate; fi && 
      php artisan migrate:fresh --seed --force && 
      npm run build && php-fpm"

  nginx:
    image: nginx:stable-alpine
    container_name: crm_nginx
    restart: unless-stopped
    ports:
      - "1000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - db
    command: [ "/bin/sh", "-c", "sleep 10 && nginx -g 'daemon off;'" ]

  db:
    image: postgres:16-alpine
    container_name: crm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mini_crm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
